---
title: "Monitoramento das Metas do Plano Nacional de Educação nos Municípios da Região Norte"
author: "Núcleo de Pesquisa em Ciência de Dados e Otimização"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
editor_options: 
  markdown: 
    wrap: 72
bibliography: ref.bib
link-citations: yes
---

### Introdução
A busca pela universalização do acesso à educação e da melhoria da qualidade de ensino é uma meta perseguida pela sociedade brasileira há bastante tempo. Nesta direção, o Plano Nacional de Educação (PNE), aprovado pela Lei 13.005/2014, e com vigência entre 2014 e 2024, constitui um marco fundamental nas políticas públicas educacionais brasileiras. O PNE possui 20 metas e conferem ao País um horizonte para o qual os esforços dos entes federativos e da sociedade civil devem convergir com a finalidade de consolidar um sistema educacional capaz de concretizar o direito à educação em sua integralidade, dissolvendo as barreiras para o acesso e a permanência, reduzindo as desigualdades, promovendo os direitos humanos e garantindo a formação para o trabalho e para o exercício autônomo da cidadania (BRASIL, 2014, 2015).

O PNE possui metas estruturantes, que visam a garantia do direito à educação básica com qualidade, que dizem respeito ao acesso, à universalização da alfabetização e à ampliação da escolaridade e das oportunidades educacionais, metas com vistas à redução das desigualdades e à valorização da diversidade, e metas para a valorização dos profissionais da educação, considerada estratégica para que as metas anteriores sejam atingidas.

O Ministério da Educação publicou o 1º, 2º e 3º Relatórios referentes aos ciclos de monitoramento das metas do PNE: biênio 2014-2016, 2016-2018 e 2008-2020, exercendo, assim, sua atribuição de publicar, a cada dois anos, estudos para aferir o cumprimento das metas estabelecidas no PNE, conforme determina a Lei nº 13.005/2014.

Esta publicação faz parte de um conjunto de ações realizadas pelo Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP), voltadas à produção e disseminação de informações e a estudos direcionados a subsidiar o monitoramento do PNE, bem como à formulação, implementação e avaliação de políticas públicas na área da educação.

Apesar de importantes, os relatórios de monitoramento do INEP consolidam os resultados dos estados, por região e nacional, não estando disponívies análise em nível municipal. Diante disso, este trabalho pretende seguir a mesma metodologia utilizado pelo INEP e propor uma metodologia que permita a análise dos indicadores do PNE em nível municipa.

Como estudo de caso, pretende-se calcular os indicadores do PNE para a a Microrregião de Itacoatiara, composta pelos municípios de Itacoatiara, Itapiranga, Nova Olinda do Norte, Silves e Urucurituba, que fazem parte da Mesorregião denominada de Centro Amazonense, correspondendo a uma população de 177.387 habitante (IBGE, 2018), baseando-se no que nisto o objetivo geral deste trabalho é Realizar o monitoramento das metas estabelecidas
nos Planos Municipais de Educação nos municípios de Itacoatiara, Itapiranga, Nova Olinda do Norte, Silves e Urucurituba, que formam a microrregião de Itacoatiara, levando em consideração a importância de conhecer a realidade educacional desta microrregião e apresenta-la para a sociedade.

O Painel de Monitoramento do PNE pode ser acessado em: <https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/inep-data/painel-de-monitoramento-do-pne>

### Objetivo Geral: 

 Calcular a Meta 1 do PNE para a Microrregião de Itacoatiara, como base para o aprendizado que que permita, posteriormente, calcular todas as 20 metas, bem como seus inicadores.

 Meta 1:Universalizar, até 2016, a educação infantil na pré-escola para as crianças de 4 (quatro) a # 5 (cinco) anos de idade e ampliar a oferta de educação infantil em creches de forma a atender, # no mínimo, 50% (cinquenta por cento) das crianças de até 3 (três) anos até o final da vigência # deste PNE.

 Objetivos Especiíficos
 
 1) Calcular o indicador 1A: Percentual da população de 4 e 5 anos que frequenta a escola
 
 2) Calcular o indicador 1B: Percentual da população de 0 a 3 anos que frequenta a escola

### Importação e Tratamento dos Dados

A primeira base que ser importada: Projeção da população brasileira: 2010-2060.

Importante: Esta base contem a estimativa da população brasileira distribuida por idade (0 a 90+ anos). Ela será usada para estimar a distribuição das idades nos municípios, dado não haver desagregação das idades em nível municipal.

# References {-}

```{r, include=FALSE}
knitr::write_bib(c('knitr', 'rmarkdown', 'xaringan'), 'packages.bib')
```
